blog/urls.py
from django.urls import path
from blog.views import *

from blog.feeds import LatestEntriesFeed


app_name = 'blog'

urlpatterns = [
    # path(' url ',' view ')
    path('', blog_home, name='home' ),
    # path('single/', blog_single, name='single' ),
    path('<int:pid>', blog_single, name='single' ),
    path('category/<str:cat_name>', blog_home, name='category' ),
    path('author/<str:author_username>', blog_home, name='author' ),
    path('tag/<str:tag_name>', blog_home, name='tag' ),
    path('search/', blog_search, name='search' ),
    path('testblog/', test_blog, name='testblog' ),
    path("rss/feed/", LatestEntriesFeed()),
    path('testform/', test_form, name='testform' ),
    # path('post-<int:pid>', dynamictest, name='dynamictest' )
    # path('<str:name>/<str:family_name>/<int:age>', dynamictest, name='dynamictest' )
    # path('<str:name>/lastname/<str:family_name>/age/<int:age>', dynamictest, name='dynamictest' )

]

djangoproj/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps = {
    "static": StaticViewSitemap,
    "blog" : BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",)
]



urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.

    
class Category(models.Model):
    name=models.CharField(max_length=255)
    
    def __str__(self):
        return self.name

class post(models.Model):   
    image = models.ImageField(upload_to='blog/',default='blog/default.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    # author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=255)                
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True) 
    updated_date = models.DateTimeField(auto_now=True)
    
    # meta dar hamon admin zaher mishe
    class Meta:
        ordering = ['created_date']
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'
        
    
    def __str__(self):
        return " {} - {} ".format(self.title,self.id)
    
    def snippets(self):
        return self.content[:100]+'...'
    
        # for /sitemap.xml + add a button in admin/post
    def get_absolute_url(self):
        return reverse('blog:single',kwargs={'pid':self.id})
    
class comments(models.Model):
    Post = models.ForeignKey(post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['created_date']
        verbose_name = 'نظر'
        verbose_name_plural = 'نظرات'

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import comments
from captcha.fields import CaptchaField

class CommentForm(forms.ModelForm):
    
    class Meta:
        model = comments
        #  fields mean things to get from user
        fields = ['name','email','subject','message', 'Post']

blog/views.py
# from django.http import HttpResponse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render,get_object_or_404
from django.urls import reverse
from blog.models import post, comments
from website.models import contact
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from website.forms import NameForm,ContactForm
from blog.forms import CommentForm
from taggit.models import Tag
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# @login_required
def blog_home(request,**kwargs):
    # posts = post.objects.all()
    posts = post.objects.filter(status=1)
    # if not len(kwargs)>0:
    #     pass
    if kwargs.get('cat_name') != None:
        posts = posts.filter(category__name=kwargs['cat_name']) 
    if kwargs.get('author_username') != None:
        posts = posts.filter(author__username = kwargs['author_username'])
    if kwargs.get('tag_name') != None:
        posts = posts.filter(tags__name__in=[kwargs['tag_name']])
    # paginator ( input , 3 = count of posts in one page   ) 
    posts = Paginator(posts,3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    tags = Tag.objects.all()
    context = {'posts':posts, 'tags':tags}
    return render(request,'blog/blog-home.html',context)

# def blog_category(request,cat_name):
#     posts = post.objects.filter(status=1)
#     # looks for name __name insted of id
#     posts = posts.filter(category__name=cat_name)  
#     context = {'posts':posts}
#     return render(request,'blog/blog-home.html',context)

# def blog_single(request):
#     content = {'title':'bitcoin', 'text':'bitcoin is the best', 'writer':'great Matin'}
#     return render(request,'blog/blog-single.html',content)

def blog_single(request,pid):
    if request.method == "POST": 
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'succed')
        else:
            messages.add_message(request,messages.ERROR,'error')
    # filter kardim ta karbar be sorat dasti natone be post hay publish nashode dast peyda kone
    posts = post.objects.filter(status=1)
    mypost = get_object_or_404(posts,pk=pid)
    # mypost = post.objects.get(id=pid)
    if not mypost.login_require:
        comment = comments.objects.filter(Post=mypost.id,approved=True).order_by('-created_date')
        form = CommentForm()
        context = {'mypost':mypost,'comment':comment, 'form':form}
        return render(request,'blog/blog-single.html',context)
    else:
        return HttpResponseRedirect(reverse('accounts:login'))


def test_blog(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        c = contact()
        c.Name = name 
        c.email = email
        c.subject = subject
        c.message = message
        c.save()
        
        print(name,email,subject,message)
    if request.method == 'GET':
        print("GET")
        
    posts = post.objects.all()
    # posts = post.objects.filter(satus=1)
    context = {'posts':posts}
    return render(request,'blog/testblog.html',context)


# def dynamictest(request,name,family_name,age):   
#     context = {'name':name,'family_name':family_name,'age':age}
#     return render(request,'blog/dynamictest.html',context)

def dynamictest(request,pid): 
    posts = post.objects.all()
    # mypost = post.objects.get(id=pid)
    # pk : primary key
    mypost = get_object_or_404(post,pk=pid)
    context = {'pid':pid, 'posts':posts,'mypost':mypost}
    return render(request,'blog/dynamictest.html',context)

def blog_search(request):
    # request.__dict__ -> shows objects in request
    # print(request.__dict__)
    posts = post.objects.filter(status=1)    
    if request.method == 'GET':
        # print('get request')
        # s:= -> if there is a s print it in s
        if s:= request.GET.get('s'):
            posts = posts.filter(content__contains=s)
        
    context = {'posts':posts}
    return render(request,'blog/blog-home.html',context)

def test_form(request):
    if request.method == 'POST':
        # form = NameForm(request.POST)
        form = ContactForm(request.POST)
        if form.is_valid():
            # name = form.cleaned_data['Name']
            # subject = form.cleaned_data['subject']
            # email = form.cleaned_data['email']
            # message = form.cleaned_data['message']
            # c = contact()
            # c.Name = name 
            # c.email = email
            # c.subject = subject
            # c.message = message
            # c.save()
            # instead of all lines above just one line does the job
            form.save()
            return HttpResponse('done')
        else:
            return HttpResponse('not valid')
        
    # form = NameForm()
    form = ContactForm()
    return render(request,'blog/testform.html', {'form':form})


def adwaam(one, two):
    """
    Purpose: one
    """
    
# end def

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt="" /></a>
    test
</div>

templates/blog/blog-home.html
{% extends "base.html" %} {% load static %} {% load blog_tags %}
{% block content %}

<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content blog-header-content col-lg-12">
        <h1 class="text-white">Dude You’re Getting a Telescope</h1>
        <p class="text-white">
          There is a moment in the life of any aspiring astronomer that it is
          time to buy that first
        </p>
        <a href="blog-single.html" class="primary-btn">View More</a>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget1.jpg' %}"
                  alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">
                  Social life
                </h4>
                <span></span>
                <p>Enjoy your social life together</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget2.jpg' %}"
                  alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                <span></span>
                <p>Be a part of politics</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img class="content-image img-fluid d-block mx-auto" src="{% static 'img/blog/cat-widget3.jpg' %}"
                  alt="" />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Food</h4>
                <span></span>
                <p>Let the food be finished</p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 posts-list">
        {% for post in posts %}
        <div class="single-post row">
          <div class="col-lg-3 col-md-3 meta-details">
            <ul class="tags">

              <!-- {% for cat in post.category.all %}
              <li><a href="#">{{ cat.name }}</a></li>,
              {% endfor %} -->

              <!-- {{ post.category.all|join:", "}} -->

              <!-- <li>
                {{post.category.all}}
              </li> -->

              {% for cat in post.category.all %}
              <a href="{% url 'blog:category' cat_name=cat.name %}">{{ cat }}</a> {% if not forloop.last %} , {% endif %}
              <!-- {{ cat.name }} -->
              {% endfor %}

            </ul>
            <div class="user-details row">
              <p class="user-name col-lg-12 col-md-12 col-6">
                <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a> <span class="lnr lnr-user"></span>
              </p>
              <p class="date col-lg-12 col-md-12 col-6">
                <a href="#">{{ post.published_date|date:"Y/m/d" }}</a>
                <span class="lnr lnr-calendar-full"></span>
              </p>
              <p class="view col-lg-12 col-md-12 col-6">
                <a href="#">{{ post.counted_views }} Views</a> <span class="lnr lnr-eye"></span>
              </p>
              <p class="comments col-lg-12 col-md-12 col-6">
                <a href="#">{% comments_count post.id %} Comments</a> <span class="lnr lnr-bubble"></span>
              </p>
            </div>
          </div>
          <div class="col-lg-9 col-md-9">
            <div class="feature-img">
              <img class="img-fluid" src="{{post.image.url}}" alt="" />
            </div>

            <a class="posts-title" href="{% url 'blog:single' pid=post.id %}">
              <h3>{{ post.title }}</h3>
            </a>
            <p class="excert">
              <!-- {{ post.snippets }} -->
              {{ post.content|truncatechars:30|safe }}
              _ {{ post.image }} _
              {{ post.image.url }}

            </p>
            <a href="#" class="primary-btn">View More</a>
          </div>
        </div>
        {{post}}
        {% endfor %}


        <nav class="blog-pagination justify-content-center d-flex">
          <ul class="pagination">
            {% if posts.has_previous %}
            <li class="page-item">
              <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                <span aria-hidden="true">
                  <span class="lnr lnr-chevron-left"></span>
                </span>
              </a>
            </li>
            {% endif %}
            {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
            <li class="page-item active"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
            {%else%}
            <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
            {% endif %}
            {% endfor %}
            {% if posts.has_next %}
            <li class="page-item">
              <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                <span aria-hidden="true">
                  <span class="lnr lnr-chevron-right"></span>
                </span>
              </a>
            </li>
            {% endif %}
          </ul>

        </nav>
      </div>
      <div class="col-lg-4 sidebar-widgets">
        <div class="widget-wrap">
          

          {% include 'blog/blog-search.html' %}

          {% include 'blog/blog-writer.html' %}

          {% latestposts 2 %}

          {% include 'blog/blog-ads.html' %}

          {% postcategories %}

          <div class="single-sidebar-widget newsletter-widget">
            <h4 class="newsletter-title">Newsletter</h4>
            <p>
              Here, I focus on a range of items and features that we use in life
              without giving them a second thought.
            </p>
            <div class="form-group d-flex flex-row">
              <div class="col-autos">
                <div class="input-group">
                  <div class="input-group-prepend">
                    <div class="input-group-text">
                      <i class="fa fa-envelope" aria-hidden="true"></i>
                    </div>
                  </div>
                  <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email"
                    onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" />
                </div>
              </div>
              <a href="#" class="bbtns">Subcribe</a>
            </div>
            <p class="text-bottom">You can unsubscribe at any time</p>
          </div>
          <div class="single-sidebar-widget tag-cloud-widget">
            <h4 class="tagcloud-title">Tag Clouds</h4>
            <ul>
              {% for tag in tags %}
              <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{ tag.name }}</a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End post-content Area -->
{% endblock %}

templates/blog/blog-popular-posts.html
{% load static %} {% load humanize %}
<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Popular Posts</h4>
    <div class="popular-post-list">
        {% for post in posts %}
        <div class="single-post-list d-flex flex-row align-items-center">
            <div class="thumb">
                <img class="img-fluid" src="{{post.image.url}}" alt="" />
            </div>
            <div class="details">
                <a href="{% url 'blog:single' pid=post.id %}">
                    <h6>{{ post.title }}</h6>
                </a>
                <p>me : {{post.published_date|date:"Y/M/d"}}</p>
                <p>nat day : {{post.published_date|naturalday}}</p>
                <p>nat time : {{post.published_date|naturaltime}}</p>
                <p>apnumber : {{1|apnumber}}</p>
                <p>intcomma : {{100000000000|intcomma}}</p>
                <p>intword : {{100000000000|intword}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

templates/blog/blog-post-categories.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
        {% for name,count in categories.items %}
        <li>
            <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
                <p>{{name}}</p>
                <p>{{count}}</p>
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-search.html
{% load static %}
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}" method="get">
        <input placeholder="Search Posts" name="s" type="text" onfocus="this.placeholder = ''"
            onblur="this.placeholder = 'Search Posts'" />
        <button type="submit"><i class="fa fa-search"></i></button>
    </form>
</div>

templates/blog/blog-writer.html
{% load static %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="" />
    <a href="#">
        <h4>Charlie Barber</h4>
    </a>
    <p>Senior blog writer</p>
    <ul class="social-links">
        <li>
            <a href="#"><i class="fa fa-facebook"></i></a>
        </li>
        <li>
            <a href="#"><i class="fa fa-twitter"></i></a>
        </li>
        <li>
            <a href="#"><i class="fa fa-github"></i></a>
        </li>
        <li>
            <a href="#"><i class="fa fa-behance"></i></a>
        </li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do
        not understand why you should have to spend money on boot camp
        when you can get. Boot camps have itssuppor ters andits
        detractors.
    </p>
</div>

templates/blog/dynamictest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{{posts}}</p>
    <h1>---</h1>
    <h1>pid = {{pid}}</h1>
    <p>{{mypost.title}} : {{mypost.content}}</p>
    <p>
        <!-- kifam dahan
        {{ name }}
        {{ family_name }}
        {{ age }}
        sale az ghazvin -->
    </p>
</body>
</html>

templates/blog/testblog.html
{% load blog_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- <p>

        {{posts}}
    {% for post in posts %}
        {% if post.status == 1 %}
            <h1>{{post.title}}</h1>
            <p>{{post.content}}</p>
            <small>{{post.published_date}}</small>
        {% endif %}
    {% endfor %}
    </p> -->
    
    {% totalposts as tp %}
    total posts we have :
    {{ tp }}
    <br>
    {% for post in posts %}
        <p>
        <!-- {{ post.content|snippet }}... -->
        {{post.content|snippet:10}}
        </p>
    {% endfor %}

    <h1>-----------</h1>

    <p>
        popular posts are : {% popularposts %}
    </p>
    <h1>------------------------------------------------------</h1>
    <form action="{%  url 'blog:testblog'  %}" method="post"><br>
        {% csrf_token %}
        <label>name:</label>
        <input type="text" name="name"><br>
        <label>email:</label>
        <input type="email" name="email"><br>
        <label>subject:</label>
        <input type="text" name="subject"><br>
        <label>message:</label>
        <input type="text" name="message"><br>
        <button type="submit">submit</button>
    </form>
    
</body>
</html>

templates/blog/testform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <form action="{%  url 'blog:testform'  %}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <!-- {{form.as_table}} -->
        <!-- {{form.as_ul}} -->
        <button type="submit">submit</button>
    </form>

</body>
</html>